export const doctors = [
  {
    id: 'rupinder-kaur',
    name: 'Dr. Rupinder Kaur',
    role: 'Senior Consultant · OBS & GYNAE',
    specialties: ['Fertility Specialist', 'High-Risk Pregnancy', 'Laparoscopic Surgery'],
    experience: '18+ Years',
    patients: '12,400+',
    deliveries: '6,800+',
    bio: 'A warm and deeply respected obstetrician, Dr. Rupinder has guided thousands of mothers through the most precious chapter of their lives. Trained at AIIMS and fellow of IFS, she is known for her patient-first approach and hands-on care during complex pregnancies.',
    qualifications: ['MBBS · AIIMS Delhi', 'MS Obstetrics & Gynaecology', 'Fellow · Indian Fertility Society', 'Member · FOGSI'],
    image: 'https://images.pexels.com/photos/19357672/pexels-photo-19357672.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    accent: 'from-blush-400 to-blush-600',
    schedule: ['Mon · 10 AM – 2 PM', 'Tue · 10 AM – 2 PM', 'Thu · 10 AM – 2 PM', 'Sat · 10 AM – 1 PM'],
  },
  {
    id: 'mrigind-singh',
    name: 'Dr. Mrigind Singh',
    role: 'Consultant Neonatologist & Pediatrician',
    specialties: ['Neonatology', 'Pediatric ICU', 'Developmental Pediatrics'],
    experience: '14+ Years',
    patients: '9,200+',
    nicu: '4,100+',
    bio: 'Dr. Mrigind brings rare tenderness and sharp clinical instinct to every tiny patient. A fellowship-trained neonatologist, he leads the NICU at Fateh with a philosophy of gentle, family-centred care — because the smallest patients deserve the most thoughtful medicine.',
    qualifications: ['MBBS · PGIMER Chandigarh', 'MD Pediatrics', 'Fellowship · Neonatology (IAP)', 'NNF Certified'],
    image: 'https://images.pexels.com/photos/19357674/pexels-photo-19357674.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    accent: 'from-sky-400 to-sky-600',
    schedule: ['Mon · 4 PM – 8 PM', 'Wed · 10 AM – 2 PM', 'Fri · 4 PM – 8 PM', 'Sun · On-call'],
  },
];

export const services = [
  {
    id: 'maternity',
    title: 'Obstetrics & Maternity',
    short: 'From the first heartbeat to the first cry — care that feels like home.',
    description: 'Luxury birthing suites, 24/7 obstetric anesthesia, and a team that respects every birth plan. Normal, assisted, and C-section deliveries handled with precision and warmth.',
    icon: '🤱',
    color: 'from-blush-400 to-blush-600',
    bg: 'bg-blush-50',
    features: ['Luxury birthing suites', 'Painless delivery options', 'Lactation support', 'Partner-friendly rooms'],
  },
  {
    id: 'gynecology',
    title: 'Gynecology',
    short: 'Preventive, surgical, and hormonal care for every stage of womanhood.',
    description: 'From adolescent consultations to menopause management, our gynaecologists combine empathy with advanced minimally-invasive techniques.',
    icon: '🌸',
    color: 'from-pink-400 to-rose-500',
    bg: 'bg-pink-50',
    features: ['Laparoscopic surgery', 'Cancer screening', 'PCOD management', 'Menopause care'],
  },
  {
    id: 'fertility',
    title: 'Fertility & IVF',
    short: 'Evidence-led fertility treatments with deeply personal support.',
    description: 'IUI, IVF, ICSI, and ovulation induction under one roof. We walk with couples through every cycle with honesty, science, and hope.',
    icon: '🌱',
    color: 'from-emerald-400 to-teal-500',
    bg: 'bg-emerald-50',
    features: ['IUI & IVF', 'ICSI procedures', 'Ovulation induction', 'Fertility preservation'],
  },
  {
    id: 'pediatrics',
    title: 'Pediatrics',
    short: 'Playful clinics. Serious medicine. For children 0–16.',
    description: 'Routine wellness, acute illness, developmental assessments, and chronic care — delivered by pediatricians your child will actually want to visit.',
    icon: '🧸',
    color: 'from-amber-400 to-orange-500',
    bg: 'bg-amber-50',
    features: ['Well-child visits', 'Growth tracking', 'Developmental screening', 'Acute care'],
  },
  {
    id: 'neonatology',
    title: 'Neonatology & NICU',
    short: 'A Level III NICU with gentle hands and advanced technology.',
    description: 'Round-the-clock neonatologists, servo-controlled incubators, and a family-integrated care model for the tiniest arrivals.',
    icon: '👶',
    color: 'from-sky-400 to-blue-500',
    bg: 'bg-sky-50',
    features: ['Level III NICU', '24/7 neonatologist', 'Kangaroo mother care', 'Neonatal transport'],
  },
  {
    id: 'vaccination',
    title: 'Vaccination',
    short: 'Painless, paperless immunisation — on IAP schedule.',
    description: 'Digitally-tracked vaccines from birth to adolescence. Comfort-first rooms, gentle nurses, and zero waiting time.',
    icon: '💉',
    color: 'from-violet-400 to-purple-500',
    bg: 'bg-violet-50',
    features: ['IAP schedule', 'Painless vaccines', 'Digital records', 'Travel vaccines'],
  },
  {
    id: 'high-risk',
    title: 'High-Risk Pregnancy',
    short: 'Specialist care when every detail matters most.',
    description: 'Maternal-fetal medicine, fetal echocardiography, and a multidisciplinary team for diabetes, hypertension, twins, and beyond.',
    icon: '🫀',
    color: 'from-rose-400 to-red-500',
    bg: 'bg-rose-50',
    features: ['Fetal medicine', 'Maternal ICU backup', 'Diabetes in pregnancy', 'Twin pregnancies'],
  },
  {
    id: 'pcod',
    title: 'PCOD & Menopause',
    short: 'Hormonal health, reimagined with lifestyle-first care.',
    description: 'Integrated programs combining endocrinology, nutrition, and mental wellness for women navigating PCOD, PCOS, or menopause.',
    icon: '🌷',
    color: 'from-fuchsia-400 to-pink-500',
    bg: 'bg-fuchsia-50',
    features: ['Hormonal profiling', 'Lifestyle programs', 'Nutrition coaching', 'Mental wellness'],
  },
];

export const testimonials = [
  {
    name: 'Ananya & Rohan Sharma',
    role: 'First-time parents',
    quote: 'Fateh made our first birth feel sacred. Dr. Rupinder held my hand through every contraction. The birthing suite, the nurses, the quiet dignity — it was everything we hoped for.',
    rating: 5,
    image: 'https://images.pexels.com/photos/10935456/pexels-photo-10935456.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=400',
  },
  {
    name: 'Meera Kapoor',
    role: 'Mother of twins',
    quote: 'Our twins arrived at 32 weeks. Dr. Mrigind and the NICU team gave us 18 days of hope, transparency, and miracles. Today, our boys are thriving. We owe them everything.',
    rating: 5,
    image: 'https://images.pexels.com/photos/10956983/pexels-photo-10956983.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=400',
  },
  {
    name: 'Priya Desai',
    role: 'IVF journey',
    quote: 'After 4 years of trying, Fateh became our home. The fertility team never rushed us, never judged us. Our daughter is 14 months old today — and she is our whole world.',
    rating: 5,
    image: 'https://images.pexels.com/photos/6849619/pexels-photo-6849619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=400',
  },
];

export const values = [
  { title: 'Compassion First', desc: 'Every protocol is designed around human dignity.', icon: '💗' },
  { title: 'Clinical Excellence', desc: 'Evidence-led, globally benchmarked care.', icon: '✨' },
  { title: 'Family-Centred', desc: 'Partners, parents, and siblings are always welcome.', icon: '🏡' },
  { title: 'Gentle Innovation', desc: 'Technology that serves, never overwhelms.', icon: '🌿' },
];

export const stats = [
  { value: '15+', label: 'Years of trusted care' },
  { value: '22K+', label: 'Babies welcomed' },
  { value: '40+', label: 'Specialists on staff' },
  { value: '98%', label: 'Patient satisfaction' },
];

export const gallery = [
  { url: 'https://images.pexels.com/photos/30282653/pexels-photo-30282653.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800', title: 'Delivery Suite', cat: 'Maternity', tall: true },
  { url: 'https://images.pexels.com/photos/32830266/pexels-photo-32830266.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'Gynecology Wing', cat: 'Facility' },
  { url: 'https://images.pexels.com/photos/3259628/pexels-photo-3259628.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'First Moments', cat: 'Maternity' },
  { url: 'https://images.pexels.com/photos/11782003/pexels-photo-11782003.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'Private Room', cat: 'Facility', tall: true },
  { url: 'https://images.pexels.com/photos/19963969/pexels-photo-19963969.png?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'Newborn Care', cat: 'NICU' },
  { url: 'https://images.pexels.com/photos/19550812/pexels-photo-19550812.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800', title: 'Pediatric Clinic', cat: 'Pediatrics', tall: true },
  { url: 'https://images.pexels.com/photos/3259629/pexels-photo-3259629.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'Doctor & Baby', cat: 'NICU' },
  { url: 'https://images.pexels.com/photos/19357676/pexels-photo-19357676.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=800', title: 'Bedside Care', cat: 'Maternity' },
];

export const parentArticles = [
  {
    tag: 'Pregnancy',
    title: 'The first trimester: what your body is actually doing',
    excerpt: 'A gentle, honest guide to the invisible changes happening in weeks 1–12 — and why rest is not laziness.',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/10956983/pexels-photo-10956983.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Newborn',
    title: 'The first 48 hours with your baby',
    excerpt: 'Feeding cues, sleep cycles, and the tiny rhythms that make newborn days feel less overwhelming.',
    readTime: '8 min',
    image: 'https://images.pexels.com/photos/3259628/pexels-photo-3259628.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Vaccination',
    title: 'The complete IAP vaccination schedule, decoded',
    excerpt: 'Every shot, every reason, every comfort tip — explained by our pediatricians in plain language.',
    readTime: '10 min',
    image: 'https://images.pexels.com/photos/19550812/pexels-photo-19550812.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Prenatal',
    title: 'Your hospital bag: a realistic packing list',
    excerpt: 'What you actually need, what you think you need, and what you will wish someone had told you.',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/30282653/pexels-photo-30282653.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Working',
    title: 'Working during pregnancy: a guide that respects you',
    excerpt: 'Rights, accommodations, and real talk about balancing trimesters with deadlines.',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/10935456/pexels-photo-10935456.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Milestones',
    title: 'Baby milestones: month by month, without the anxiety',
    excerpt: 'A gentle, evidence-based look at what to expect — and what to let unfold.',
    readTime: '9 min',
    image: 'https://images.pexels.com/photos/6849619/pexels-photo-6849619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Delivery',
    title: 'Preparing for delivery: mentally, physically, emotionally',
    excerpt: 'Breathing, birth plans, and the quiet confidence that comes from preparation.',
    readTime: '8 min',
    image: 'https://images.pexels.com/photos/19357672/pexels-photo-19357672.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
  {
    tag: 'Postpartum',
    title: 'The fourth trimester no one talks about',
    excerpt: 'Recovery, identity, and the emotional landscape after baby arrives.',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/31905447/pexels-photo-31905447.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=800&w=1000',
  },
];
